baseURL = "/"
languageCode = "en-us"
title = "Amy Schlesener"
theme = "min_night"

[blackfriday]
  hrefTargetBlank = true

[params]
  font = "Georgia"
  accent = "#4D4D4D"
  backgroundColor = "#efeded"
  description = "Hello!"
  logo = "favicon-3.ico"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Blog Posts"
    weight = 2
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 3

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:amy@amyschlesener.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/amyschlesener/"
    name = "linkedin"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/amyschlesener/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://github.com/aschlesener"
    name = "github"
    weight = 4
